### ISSUE TITLE
Parsing xml?

### ISSUE THREAD

**Issue by marvin2k** [sabel83/metaparse_tutorial#2]
Hi,

just stumbled over this library (tutorial), impressed so far. I wonder what the author thinks about the possibility to parse xml based on a specifc xsd, using metaparse?

In the end I would like to have something to create the interface / API out of the xsd file, and then parse one xml into the datastructure behind the API _at_compile_time_. The information described by an instance of xml should not result in any runtime parsing at all.

xml2cpp seems like a runtime version of this.

Greetings

**Comment by sabel83** [comment]
Are you thinking of having an external tool taking an xsd and generating C++ source code parsing and validating xml documents at compile-time? Or writing a C++ library taking both xsd and xml documents and validating the xml documents against the schema at compile-time?

**Comment by marvin2k** [comment]
I assume that tools like xmllint or xmlstarlet are sufficient to validate a xsd+xml database. What I'm looking for is a source-code generator: In a first step it parses the xsd to create a c++ API, and in a second step parses _one_ of the possible xml-files to create a compile-time representation of the database. Note: I have not played with metaparse so far, so there might be gross misunderstandings ;-)

This should allow fast and safe (compile time, no runtime parsing!) access to the structured data, for cases where the xml will not change after compilation. In fact it shall never be read again.

**Comment by sabel83** [comment]
You should do the first step (parsing xsd to create C++ API) with an external tool generating C++ code doing the second step (parsing one xml file) at compile-time with the generated parser.

Note that you should be able to do both steps during C++ compilation, but it will probably have a significant compile-time overhead - see http://www.boost.org/doc/libs/1_65_1/doc/html/metaparse/reference.html#grammar as an example: it parses a grammar of a language, generates a compile-time parser for that language and parses one (or more) document using that generated parser. It is the same workflow you'd like to do (grammar -> xsd, document -> xml document), but it is very slow. This is why the first step is better done with an external tool.

**Comment by marvin2k** [comment]
Ah, I see. After tooling around, the compile time overhead is indeed significant even for simple grammars. But I'm sure I'll use it sometime in the future, we'll see ;-) Thanks!
